### ISSUE TITLE
Build fails with FileNotFoundError: [Errno 2] No such file or directory: 'gtkdoc-scan'

### ISSUE THREAD

**Issue by FireFaced** [ebassi/emeus#27]
When I build Emeus, I get the following error at `sudo ninja install`

> [0/1] Installing files.
Installing src/libemeus-1.0.so.0.9901.0 to /usr/local/lib64/libemeus-1.0.so.0.9901.0
Installing src/Emeus-1.0.gir to /usr/local/share/gir-1.0/Emeus-1.0.gir
Installing src/Emeus-1.0.typelib to /usr/local/lib64/girepository-1.0/Emeus-1.0.typelib
Installing src/tools/emeus-gen-constraints to /usr/local/bin/emeus-gen-constraints
Installing src/tools/com.endlessm.EmeusEditor.desktop to /usr/local/share/applications/com.endlessm.EmeusEditor.desktop
Installing src/tools/emeus-edit-constraints to /usr/local/bin/emeus-edit-constraints
Installing examples/simple-grid to /usr/local/share/emeus-1.0/examples/simple-grid
Installing doc/emeus-gen-constraints.1 to /usr/local/share/man/man1/emeus-gen-constraints.1
Installing emeus-constraint.h to /usr/local/include/emeus-1.0
Installing emeus-constraint-layout.h to /usr/local/include/emeus-1.0
Installing emeus-version-macros.h to /usr/local/include/emeus-1.0
Installing emeus-types.h to /usr/local/include/emeus-1.0
Installing emeus-utils.h to /usr/local/include/emeus-1.0
Installing emeus.h to /usr/local/include/emeus-1.0
Installing /home/julian/dev/emeus/_build/src/emeus-version.h to /usr/local/include/emeus-1.0
Installing /home/julian/dev/emeus/_build/src/emeus-1.0.pc to /usr/local/lib64/pkgconfig
Installing /home/julian/dev/emeus/_build/src/tools/com.endlessm.EmeusEditor.service to /usr/local/share/dbus-1/services
Installing /home/julian/dev/emeus/src/tools/com.endlessm.EmeusEditor.png to /usr/local/share/icons/hicolor/256x256/apps
Installing /home/julian/dev/emeus/examples/simple-grid.c to /usr/local/share/emeus-1.0/examples
Installing /home/julian/dev/emeus/examples/simple-grid.js to /usr/local/share/emeus-1.0/examples
Installing /home/julian/dev/emeus/examples/centered.js to /usr/local/share/emeus-1.0/examples
Running custom install script '/usr/bin/python3 /usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=emeus --langs=en_GB'
Installing /home/julian/dev/emeus/_build/po/en_GB.gmo to /usr/local/share/locale/en_GB/LC_MESSAGES/emeus.mo
Running custom install script '/usr/bin/python3 /usr/bin/meson --internal gtkdoc --sourcedir=/home/julian/dev/emeus --builddir=/home/julian/dev/emeus/_build --subdir=doc --headerdirs=/home/julian/dev/emeus/src --mainfile=emeus-docs.xml --modulename=emeus --mode=auto --scanargs=--rebuild-types@@--ignore-decorators=_EMEUS_PUBLIC@@--ignore-headers=emeus.h config.h emeus-constraint-layout-private.h emeus-constraint-private.h emeus-expression-private.h emeus-macros-private.h emeus-simplex-solver-private.h emeus-types-private.h emeus-utils-private.h emeus-variable-private.h emeus-version.h emeus-vfl-parser-private.h emeus-test-utils.h --gobjects-types-file=emeus.types --fixxrefargs=--html-dir=/usr/local/share/gtk-doc/html@@--extra-dir=/usr/share/gtk-doc/html/glib@@--extra-dir=/usr/share/gtk-doc/html/gobject@@--extra-dir=/usr/share/gtk-doc/html/gtk3 --cflags=-I/home/julian/dev/emeus/_build/src/. -I/home/julian/dev/emeus/src/. -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libdrm -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread --ldflags=-L/home/julian/dev/emeus/_build/src -Wl,-rpath,/home/julian/dev/emeus/_build/src -lemeus-1.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lm --cc=cc --ld=cc'
Building documentation for emeus
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 312, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 279, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/gtkdochelper.py", line 218, in run
    options.mode)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/gtkdochelper.py", line 109, in build_gtkdoc
    gtkdoc_run_check(scan_cmd, abs_out)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/gtkdochelper.py", line 51, in gtkdoc_run_check
    p, out = Popen_safe(cmd, cwd=cwd, stderr=subprocess.STDOUT)[0:2]
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 521, in Popen_safe
    stderr=stderr, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'gtkdoc-scan'
Failed to run install script '/usr/bin/python3 /usr/bin/meson --internal gtkdoc --sourcedir=/home/julian/dev/emeus --builddir=/home/julian/dev/emeus/_build --subdir=doc --headerdirs=/home/julian/dev/emeus/src --mainfile=emeus-docs.xml --modulename=emeus --mode=auto --scanargs=--rebuild-types@@--ignore-decorators=_EMEUS_PUBLIC@@--ignore-headers=emeus.h config.h emeus-constraint-layout-private.h emeus-constraint-private.h emeus-expression-private.h emeus-macros-private.h emeus-simplex-solver-private.h emeus-types-private.h emeus-utils-private.h emeus-variable-private.h emeus-version.h emeus-vfl-parser-private.h emeus-test-utils.h --gobjects-types-file=emeus.types --fixxrefargs=--html-dir=/usr/local/share/gtk-doc/html@@--extra-dir=/usr/share/gtk-doc/html/glib@@--extra-dir=/usr/share/gtk-doc/html/gobject@@--extra-dir=/usr/share/gtk-doc/html/gtk3 --cflags=-I/home/julian/dev/emeus/_build/src/. -I/home/julian/dev/emeus/src/. -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libdrm -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread --ldflags=-L/home/julian/dev/emeus/_build/src -Wl,-rpath,/home/julian/dev/emeus/_build/src -lemeus-1.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lm --cc=cc --ld=cc'
FAILED: meson-install 
/usr/bin/python3 /usr/bin/meson --internal install /home/julian/dev/emeus/_build/meson-private/install.dat
ninja: build stopped: subcommand failed.

**Comment by ebassi** [comment]
Emeus will generate its API reference by default on installation.

You need to either have installed gtk-doc, or configure Emeus with `-Denable-gtk-doc=false`.
