### ISSUE TITLE
obvious constraints

### ISSUE THREAD

**Issue by matthiasclasen** [ebassi/emeus#35]
I wonder why emeus isn't adding the 'obvious'

width >=0
height >= 0

constraints for all widgets automatically.
When I tried that, it did seem to make things a bit more stable - I see fewer assertions on negative allocations with it.

**Comment by ebassi** [comment]
There's no actual reason, I think it would be good to add them.

**Comment by matthiasclasen** [comment]
https://github.com/ebassi/emeus/pull/37
